# Generated by Django 2.2.4 on 2019-08-30 22:23

from django.db import migrations, models
import vouchers.models


class Migration(migrations.Migration):

    dependencies = [
        ('vouchers', '0003_auto_20190831_0102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voucher',
            name='code',
            field=models.CharField(default=vouchers.models.generate_code, max_length=12),
        ),
    ]
