# Generated by Django 2.2.4 on 2019-09-07 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vouchers', '0005_auto_20190901_0031'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voucher',
            name='discount',
        ),
        migrations.AddField(
            model_name='voucher',
            name='discount_format',
            field=models.IntegerField(choices=[(1, 'RM %f'), (2, '%f% off')], default=1),
        ),
        migrations.AddField(
            model_name='voucher',
            name='discount_value',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=5),
        ),
    ]
